# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_localization.proto
"""Generated protocol buffer code."""
from src.google.protobuf.internal import builder as _builder
from src.google.protobuf import descriptor as _descriptor
from src.google.protobuf import descriptor_pool as _descriptor_pool
from src.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amessage_localization.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\x9a\x05\n\x14Message_Localization\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\r\n\x05\x61ngle\x18\x04 \x01(\x01\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x17\n\x0f\x63orrection_errs\x18\x06 \x03(\x01\x12\x15\n\rreliabilities\x18\x07 \x03(\x01\x12\x19\n\x11in_forbidden_area\x18\x08 \x01(\x08\x12\x46\n\rupdate_reason\x18\t \x01(\x0e\x32/.rbk.protocol.Message_Localization.UpdateReason\x12>\n\tloc_state\x18\n \x01(\x0e\x32+.rbk.protocol.Message_Localization.LocState\x12\x12\n\nsimilarity\x18\x0b \x01(\x01\x12@\n\nloc_method\x18\x0c \x01(\x0e\x32,.rbk.protocol.Message_Localization.LocMethod\"Z\n\x0cUpdateReason\x12\x08\n\x04None\x10\x00\x12\r\n\tOdoUpdate\x10\x01\x12\x0f\n\x0bLaserCorrec\x10\x02\x12\x10\n\x0cLaserThenOdo\x10\x03\x12\x0e\n\nPGVCORRECT\x10\x04\"7\n\x08LocState\x12\n\n\x06Normal\x10\x00\x12\x0c\n\x08Skidding\x10\x01\x12\x11\n\rLowConfidence\x10\x02\"]\n\tLocMethod\x12\x0f\n\x0bPF_LASER_2D\x10\x00\x12\x0b\n\x07SLAM_2D\x10\x01\x12\x07\n\x03PGV\x10\x02\x12\r\n\tREFLECTOR\x10\x03\x12\x0c\n\x08LASER_3D\x10\x04\x12\x0c\n\x08\x42\x41R_CODE\x10\x05\"$\n\x13Message_LocFinished\x12\r\n\x05value\x18\x01 \x01(\x08\"\xa7\x01\n\x0eMessage_3DPose\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x0b\n\x03q_w\x18\x05 \x01(\x01\x12\x0b\n\x03q_x\x18\x06 \x01(\x01\x12\x0b\n\x03q_y\x18\x07 \x01(\x01\x12\x0b\n\x03q_z\x18\x08 \x01(\x01\x12\x12\n\nextra_data\x18\t \x01(\t\"?\n\x11Message_IRCAMPose\x12*\n\x04pose\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_3DPoseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_localization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_LOCALIZATION']._serialized_start=67
  _globals['_MESSAGE_LOCALIZATION']._serialized_end=733
  _globals['_MESSAGE_LOCALIZATION_UPDATEREASON']._serialized_start=491
  _globals['_MESSAGE_LOCALIZATION_UPDATEREASON']._serialized_end=581
  _globals['_MESSAGE_LOCALIZATION_LOCSTATE']._serialized_start=583
  _globals['_MESSAGE_LOCALIZATION_LOCSTATE']._serialized_end=638
  _globals['_MESSAGE_LOCALIZATION_LOCMETHOD']._serialized_start=640
  _globals['_MESSAGE_LOCALIZATION_LOCMETHOD']._serialized_end=733
  _globals['_MESSAGE_LOCFINISHED']._serialized_start=735
  _globals['_MESSAGE_LOCFINISHED']._serialized_end=771
  _globals['_MESSAGE_3DPOSE']._serialized_start=774
  _globals['_MESSAGE_3DPOSE']._serialized_end=941
  _globals['_MESSAGE_IRCAMPOSE']._serialized_start=943
  _globals['_MESSAGE_IRCAMPOSE']._serialized_end=1006
# @@protoc_insertion_point(module_scope)
