# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_imu.proto
"""Generated protocol buffer code."""
from src.google.protobuf.internal import builder as _builder
from src.google.protobuf import descriptor as _descriptor
from src.google.protobuf import descriptor_pool as _descriptor_pool
from src.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11message_imu.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"v\n\x16Message_ImuInstallInfo\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\n\n\x02qx\x18\x04 \x01(\x01\x12\n\n\x02qy\x18\x05 \x01(\x01\x12\n\n\x02qz\x18\x06 \x01(\x01\x12\n\n\x02qw\x18\x07 \x01(\x01\x12\x0b\n\x03SSF\x18\x08 \x01(\x01\"\xe4\x02\n\x0bMessage_IMU\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x0b\n\x03yaw\x18\x02 \x01(\x01\x12\x0c\n\x04roll\x18\x03 \x01(\x01\x12\r\n\x05pitch\x18\x04 \x01(\x01\x12\r\n\x05\x61\x63\x63_x\x18\x05 \x01(\x01\x12\r\n\x05\x61\x63\x63_y\x18\x06 \x01(\x01\x12\r\n\x05\x61\x63\x63_z\x18\x07 \x01(\x01\x12\r\n\x05rot_x\x18\x08 \x01(\x01\x12\r\n\x05rot_y\x18\t \x01(\x01\x12\r\n\x05rot_z\x18\n \x01(\x01\x12\x11\n\trot_off_x\x18\x0b \x01(\x05\x12\x11\n\trot_off_y\x18\x0c \x01(\x05\x12\x11\n\trot_off_z\x18\r \x01(\x05\x12\n\n\x02qx\x18\x0e \x01(\x01\x12\n\n\x02qy\x18\x0f \x01(\x01\x12\n\n\x02qz\x18\x10 \x01(\x01\x12\n\n\x02qw\x18\x11 \x01(\x01\x12:\n\x0cinstall_info\x18\x12 \x01(\x0b\x32$.rbk.protocol.Message_ImuInstallInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_imu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_IMUINSTALLINFO']._serialized_start=57
  _globals['_MESSAGE_IMUINSTALLINFO']._serialized_end=175
  _globals['_MESSAGE_IMU']._serialized_start=178
  _globals['_MESSAGE_IMU']._serialized_end=534
# @@protoc_insertion_point(module_scope)
